package com.lefarmico.navigation.screen

enum class Screen {
    HOME_SCREEN,
    WORKOUT_SCREEN,
    SETTINGS_SCREEN,

    CREATE_NEW_EXERCISE_SCREEN,

    CATEGORY_SCREEN_FROM_LIBRARY,
    SUBCATEGORY_SCREEN_FROM_LIBRARY,
    EXERCISE_SCREEN_FROM_LIBRARY,
    EXERCISE_DETAILS_SCREEN_FROM_LIBRARY,

    CATEGORY_SCREEN_FROM_WORKOUT,
    SUBCATEGORY_SCREEN_FROM_WORKOUT,
    EXERCISE_SCREEN_FROM_WORKOUT,
    EXERCISE_DETAILS_SCREEN_FROM_WORKOUT,

    SET_PARAMETERS_DIALOG
}
