package com.lefarmico.navigation.screen

enum class Screen {
    HOME_SCREEN,
    WORKOUT_SCREEN_FROM_DETAILED_SCREEN,

    WORKOUT_SCREEN,
    EDIT_WORKOUT_RECORD_SCREEN,
    ACTION_ADD_EXERCISE_TO_WORKOUT_SCREEN,

    LIBRARY_SUBCATEGORY_LIST_SCREEN,
    LIBRARY_EXERCISES_LIST_SCREEN,
    FROM_LIBRARY_TO_EXERCISE_DETAILS,
    FROM_LIBRARY_TO_CREATE_NEW_EXERCISE,

    CATEGORY_LIST_SCREEN,
    SUBCATEGORY_LIST_SCREEN,
    EXERCISE_LIST_SCREEN,

    CREATE_NEW_EXERCISE_SCREEN,
    EXERCISE_DETAILS_SCREEN,

    EXERCISE_DETAILS_SCREEN_FROM_WORKOUT,
}
